version: '3'

services:
  web:
    build: .
    command:
      ["gunicorn", "--bind", "0.0.0.0:8000", theplaces.wsgi:application"]
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
env_file:
  - ./.local_settings.py
